[dependencies]
clap = {version = "4.5.53", features = ["derive"]}
color-eyre = "0.6.5"
console = "0.16.2"
eyre = "0.6.12"
tokio = {version = "1.48.0", features = ["full"]}

[package]
name = "nimi"
version = "0.1.0"
edition = "2024"
